### ISSUE TITLE
Simply can't get started with this. Error: Cannot find module 'dojo/dojo'

### ISSUE THREAD

**Issue by ghost** [SitePen/TypeScript-examples#1]
Frustrating when you can't even get started with the simple examples.
1. `npm install`
2. `grunt`
3. `grunt test`

`Running "intern:client" (intern) task
Error: Cannot find module 'dojo/dojo'
  at Function.Module._resolveFilename  <module.js:339:15>
  at Function.require.resolve  <internal/module.js:27:19>
  at <node_modules/intern/lib/executors/PreExecutor.js:498:32>
  at new Promise  <node_modules/intern/browser_modules/dojo/Promise.ts:411:3>
  at PreExecutor.swapLoader  <node_modules/intern/lib/executors/PreExecutor.js:489:11>
  at swapLoader  <node_modules/intern/lib/executors/PreExecutor.js:449:17>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
`

**Comment by kitsonk** [comment]
Ideally we should be depending on a version of `dojo-loader` for this instead of using the Dojo 1 loader, which, resolving it as a dependency is what is going on.

**Comment by agubler** [comment]
@tfsimondouglas the missing dependencies have been added in #3, look forward to more updates as we work through #2. Thanks for raising this.
